INSERT INTO `tbl_role` (`ROLEID`, `ROLECODE`, `ROLENAME`, `PERID`) VALUES (1, NULL, NULL, NULL);
INSERT INTO `tbl_role` (`ROLEID`, `ROLECODE`, `ROLENAME`, `PERID`) VALUES (2, NULL, NULL, NULL);
INSERT INTO `tbl_role` (`ROLEID`, `ROLECODE`, `ROLENAME`, `PERID`) VALUES (3, NULL, NULL, NULL);
